name: ReportSystem
main: net.minemora.reportsystem.ReportSystem
version: ${project.version}
author: Elecast
commands:
   spy:
      usage: /<command>
      aliases: [espiar]
   ping:
      usage: /<command>
   invsee:
      usage: /<command>